name: ObjectDetectionEnv
channels:
  - conda-forge
  - defaults
dependencies:
  # --- Core ---
  - python=3.9
  - pip
  - setuptools
  - wheel

  # --- Math / Scientific ---
  - numpy
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - h5py

  # --- 3D / Vision ---
  - open3d
  - opencv
  - trimesh
  - pyglet
  - pyopengl
  - freetype-py

  # --- Dev / Utils ---
  - tqdm
  - pyyaml
  - requests
  - configargparse
  - psutil
  - joblib
  - packaging
  - typing-extensions

  # --- Jupyter / Visualization ---
  - jupyter
  - ipywidgets
  - widgetsnbextension
  - matplotlib-inline
  - dash
  - flask
  - plotly
  - werkzeug
  - itsdangerous
  - markupsafe

  # --- Build dependencies (needed for teaserpp-python from source) ---
  - cmake
  - ninja
  - boost-cpp
  - eigen
  - libstdcxx-ng
  - gxx_linux-64  # ensures C++ compiler is available on Linux

  - pip:
      # --- Key Python packages ---
      - blenderproc==2.8.0
      #- teaserpp-python==1.1.0
      - ultralytics==8.3.176
      - torch==2.3.1
      - torchvision==0.18.1
      - triton
      - addict
      - pyrender
      - pyquaternion
      - networkx
      - faster-coco-eval
      - pillow

